# Generated by Django 5.2.4 on 2025-07-17 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='refno',
            field=models.IntegerField(default=123455677),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='refno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto1.cartitem'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='storename',
            field=models.CharField(default='Resto1'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resto1.cartitem'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='storename',
            field=models.CharField(default='Resto1'),
        ),
    ]
