# Generated by Django 5.2.4 on 2025-07-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0003_transaction_payment_method_transaction_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
