# Generated by Django 5.2.4 on 2025-07-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0004_product_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
