# Generated by Django 5.2.4 on 2025-07-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0005_transaction_items_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='refno',
        ),
    ]
