# Generated by Django 5.2.4 on 2025-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0006_remove_transaction_refno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_in_advance', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='daily_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
