# Generated by Django 5.2.4 on 2025-07-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0007_preordersettings_product_daily_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='daily_limit',
        ),
        migrations.CreateModel(
            name='ProductLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resto1.product')),
            ],
        ),
    ]
