# Generated by Django 5.2.4 on 2025-07-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto1', '0009_product_daily_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='daily_limit',
        ),
    ]
