# Generated by Django 5.2.4 on 2025-07-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='restoname',
            new_name='name',
        ),
    ]
