# Generated by Django 5.2.4 on 2025-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_restoname_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
