# Generated by Django 5.2.4 on 2025-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_home_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
