# Generated by Django 5.2.4 on 2025-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_home_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
